# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      version = "~> 3.74"
    }
  }
  backend "s3" {
    bucket         = "dojo-dx-exp-tfstate"
    dynamodb_table = "dojo-dx-exp-tflock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-northeast-1"
  }
}
